[project]
name = "dashplot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dash>=3.2.0",
    "dash-bootstrap-components>=2.0.3",
    "dash-design-kit>=0.0.1",
    "pandas>=2.3.1",
    "plotly>=6.3.0",
]
